import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider, SignedIn, SignedOut, SignIn, SignUp, UserButton } from "@clerk/nextjs";
import ResponsiveAppBar from '../components/Header'
import Link from "next/link";
import Header from "../components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    <html lang="en">
      <body className={inter.className}>
      <ClerkProvider appearance={{
      variables:{
        colorPrimary:"#624cf5"
      }
    }}>
         <Header />
          {children}
    </ClerkProvider>
      </body>
    </html>
  );
}
