import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider, SignedIn, SignedOut, SignIn, SignUp, UserButton } from "@clerk/nextjs";
import ResponsiveAppBar from '../components/header'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider appearance={{
      variables:{
        colorPrimary:"#624cf5"
      }
    }}>
    <html lang="en">
      <body className={inter.className}>
      <ResponsiveAppBar/>
      <SignedOut>
          <SignIn routing="/" appearance={{
            elements:{
              rootBox:{ 
                position:'absolute',
                top:'50%',
                left:'50%',
                transform:'translate(-50%,-50%)'
                }
              }
          }} ></SignIn>
        </SignedOut>
        <SignedIn>
          {children}
        </SignedIn>
      </body>
    </html>
    </ClerkProvider>
  );
}
