import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider, SignedIn, SignedOut, SignIn, SignUp, UserButton } from "@clerk/nextjs";
import ResponsiveAppBar from '../components/Header'
import Link from "next/link";
import Header from "../components/Header";
import { GoogleAnalytics } from '@next/third-parties/google'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ChatPage",
  description: "Generated by create next app",
};

// const MEASUREMENT_ID = "G-GS8VXH6H9X"
// ReactGA.initialize(MEASUREMENT_ID)
// ReactGA.send({ hitType: "pageview", page: "https://ai-customer-chatbot-omega.vercel.app", title: "ChatPage" });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
      <ClerkProvider appearance={{
      variables:{
        colorPrimary:"#624cf5"
      }
    }}>
    <html lang="en">
      <body className={inter.className}>
         <Header />
          {children}
      </body>
          <GoogleAnalytics gaId="G-GS8VXH6H9X" />
    </html>
    </ClerkProvider>
  );
}
